### ISSUE TITLE
Folder names should not end with dots

### ISSUE THREAD

**Issue by sadasant** [PvrpleBlvck/Python_Learning_Journey#1]
Folder names ending with dots are something we don’t usually see in the wild. I would rather not end folder names with dots 🙂

---

Try solving this issue by making a pull request to your own project! Follow this tutorial: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

Also, when you post that pull request, make sure to reference this issue. Read the following: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by PvrpleBlvck** [comment]
Much appreciated, I will follow the link and make use of it.
